let employee=[
{"id":1,
"first_name":"Bernardine",
"last_name":"Banbrook",
"email":"bbanbrook0@shareasale.com",
"gender":"Male"
},
{
    "id":2,
    "first_name":"Corrie",
    "last_name":"Toffalo",
    "email":"ctoffalo1@ovh.net",
    "gender":"Genderqueer"
},
{
    "id":3,
    "first_name":"Calli",
    "last_name":"Golsby",
    "email":"cgolsby2@sfgate.com",
    "gender":"Female"
}]